apiVersion: apps/v1
kind: Deployment
metadata:
  name: trustflow-app
  namespace: trustflow
spec:
  template:
    spec:
      containers:
        - name: app
          image: ghcr.io/amirmahdy/trustflow-app@sha256:bc227f02f2e9b302fdc61aa5883763c075dafba962af85755fdfc7d3e874ed12
