apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-image-digest
spec:
  validationFailureAction: Enforce
  background: true
  rules:
    - name: require-digest-containers
      match:
        any:
          - resources:
              kinds:
                - Pod
      validate:
        message: "Container images must be pinned by digest (image@sha256:...)."
        foreach:
          - list: "request.object.spec.containers"
            deny:
              conditions:
                any:
                  - key: "{{ regex_match('^.+@sha256:[a-f0-9]{64}$', element.image) }}"
                    operator: Equals
                    value: false
    - name: require-digest-initcontainers
      match:
        any:
          - resources:
              kinds:
                - Pod
      preconditions:
        all:
          - key: "{{ request.object.spec.initContainers || `[]` | length(@) }}"
            operator: GreaterThan
            value: 0
      validate:
        message: "InitContainer images must be pinned by digest (image@sha256:...)."
        foreach:
          - list: "request.object.spec.initContainers"
            deny:
              conditions:
                any:
                  - key: "{{ regex_match('^.+@sha256:[a-f0-9]{64}$', element.image) }}"
                    operator: Equals
                    value: false
