apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-image-digest
spec:
  validationFailureAction: Enforce
  background: true
  rules:
    - name: require-digest-containers
      match:
        any:
          - resources:
              kinds:
                - Pod
      validate:
        message: "Container images must be pinned by digest (image@sha256:...)."
        foreach:
          - list: "request.object.spec.containers"
            deny:
              conditions:
                any:
                  - key: "{{ element.image }}"
                    operator: NotMatches
                    value: ".+@sha256:[a-f0-9]{64}$"
    - name: require-digest-initcontainers
      match:
        any:
          - resources:
              kinds:
                - Pod
      preconditions:
        all:
          - key: "{{ request.object.spec.initContainers }}"
            operator: NotEquals
            value: null
      validate:
        message: "InitContainer images must be pinned by digest (image@sha256:...)."
        foreach:
          - list: "request.object.spec.initContainers"
            deny:
              conditions:
                any:
                  - key: "{{ element.image }}"
                    operator: NotMatches
                    value: ".+@sha256:[a-f0-9]{64}$"
