apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-server
  namespace: argocd
spec:
  template:
    spec:
      initContainers:
        - name: extension-trivy
          image: quay.io/argoprojlabs/argocd-extension-installer:v0.0.9@sha256:d2b43c18ac1401f579f6d27878f45e253d1e3f30287471ae74e6a4315ceb0611
          env:
            - name: EXTENSION_NAME
              value: extension-trivy
            - name: EXTENSION_URL
              value: https://github.com/mziyabo/argocd-trivy-extension/releases/latest/download/extension-trivy.tar
            - name: EXTENSION_VERSION
              value: latest
            - name: EXTENSION_CHECKSUM_URL
              value: https://github.com/mziyabo/argocd-trivy-extension/releases/latest/download/extension-trivy_checksums.txt
          volumeMounts:
            - name: extensions
              mountPath: /tmp/extensions/
          securityContext:
            runAsUser: 1000
            allowPrivilegeEscalation: false
        - name: extension-trustflow
          image: quay.io/argoprojlabs/argocd-extension-installer:v0.0.9@sha256:d2b43c18ac1401f579f6d27878f45e253d1e3f30287471ae74e6a4315ceb0611
          env:
            - name: EXTENSION_NAME
              value: extension-trustflow
            - name: EXTENSION_URL
              value: https://github.com/amirmahdy/trustflow-argocd-extension/raw/refs/heads/master/dist/extension-trustflow.tar
            - name: EXTENSION_VERSION
              value: v0.1.0
          volumeMounts:
            - name: extensions
              mountPath: /tmp/extensions/
          securityContext:
            runAsUser: 1000
            allowPrivilegeEscalation: false
        - name: extension-trustflow-fix
          image: quay.io/argoprojlabs/argocd-extension-installer:v0.0.9@sha256:d2b43c18ac1401f579f6d27878f45e253d1e3f30287471ae74e6a4315ceb0611
          command: ["sh", "-c"]
          args:
            - "sed -i 's|\\${appNamespace}/\\${appName}|\\${appNamespace}:\\${appName}|g' /tmp/extensions/resources/trustflow/extension-trustflow.js"
          volumeMounts:
            - name: extensions
              mountPath: /tmp/extensions/
          securityContext:
            runAsUser: 1000
            allowPrivilegeEscalation: false
      containers:
        - name: argocd-server
          volumeMounts:
            - name: extensions
              mountPath: /tmp/extensions/
      volumes:
        - name: extensions
          emptyDir: {}
