apiVersion: apps/v1
kind: Deployment
metadata:
  name: trustflow-app
  namespace: trustflow
spec:
  template:
    spec:
      containers:
        - name: app
          image: ghcr.io/YOUR_GITHUB_ORG_OR_USER/trustflow-app@sha256:0000000000000000000000000000000000000000000000000000000000000000

